In [2]:
import numpy as np


In [19]:
arr = np.array([[10,20,30,40],[50,60,80,90],[20,30,70,80]])
print(arr)
print(type(arr))
print(arr[1:3,1:3])


[[10 20 30 40]
 [50 60 80 90]
 [20 30 70 80]]
<class 'numpy.ndarray'>
[[60 80]
 [30 70]]


In [24]:
print(np.shape(arr))
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

(3, 4)
12
2
int64


In [32]:
print(arr.shape)  #rows, columns
print(len(arr))   #number of nested values
print(arr.size)   #number of elements
print(arr.dtype)  #datatype of array
print(type(arr))  #data type of variable
print(arr.astype(str))  #conversion of data type

(3, 4)
3
12
int64
<class 'numpy.ndarray'>
[['10' '20' '30' '40']
 ['50' '60' '80' '90']
 ['20' '30' '70' '80']]
